baseurl = "https://blog.tcweb.org"
languageCode = "fr-fr"
title = "TcWeb"
description = "Le blog de Thomas Clavier"
theme = "tcweb"
DisqusShortname="blogtcweb"

Paginate = 10

[taxonomies]
tag = "tags"
category = "categories"
