#!/bin/bash
API=http://tcweb.org/mediawiki/api.php
INDEX=http://tcweb.org/mediawiki/index.php
DIR=$(dirname $0)
CACHE=$DIR/cache
CONTENT=$DIR/../content/wiki

[ -d $CACHE ] || mkdir -p $CACHE
[ -d $CONTENT ] || mkdir -p $CONTENT

slug() {
  input=$1
  echo "$input" | iconv --from-code utf-8 --to-code us-ascii//TRANSLIT | tr '[:upper:]' '[:lower:]'| sed -e 's/[^a-z0-9]/ /g' -e 's/[ ]\+/ /g' -e 's/^ //' -e 's/ $//' -e 's/ /-/g'
}

LST_PAGES=$CACHE/liste_pages
[ -f $LST_PAGES ] || wget -q -O $LST_PAGES "$API?action=query&list=allpages&format=json&aplimit=500"

#LST_IMG=$CACHE/liste_img
#[ -f $LST_IMG ] || wget -q -O $LST_IMG "$API?action=query&list=allimages&format=json&aplimit=500"

rm -f $CACHE/links.sed

for page in $(cat $LST_PAGES | jq -r '.query.allpages[].pageid')
do
  echo -n "$page : "
  META=$CACHE/${page}.json
  [ -f $META ] || wget -q -O $META "$API?action=query&prop=revisions&pageids=$page&format=json"
  TITLE=$(cat $META | jq -r '.query.pages[].title' )
  DATE=$(cat $META | jq -r '.query.pages[].revisions[].timestamp')
  DATE=$(date -d $DATE +%Y-%m-%d)

  RAW=$CACHE/${page}.raw
  [ -f $RAW ] || wget -q -O $RAW "$INDEX?title=$TITLE&action=raw" 

  SLUG=$(slug "$TITLE")
  echo -n "$TITLE -> $SLUG "
  DST=$CONTENT/$SLUG.md
  REGEX=$(echo $TITLE| sed -e 's?/?\\/?g' -e 's/"/\\"/g')
  echo "s/$REGEX \"wikilink\"/\/$SLUG/g" >> $CACHE/links.sed
 
  EXCLUDE=0
  REDIRECT=$(grep -ic '#REDIRECT' $RAW)
  [ $REDIRECT -gt 0 ] && EXCLUDE=1
  WORDS=$(cat $RAW| wc -c)
  [ $WORDS -eq 0 ] && EXCLUDE=1
  FIND=$(egrep -c "^$SLUG$" $DIR/excludes.lst)
  [ $FIND -gt 0 ] && EXCLUDE=1

  if [ $EXCLUDE -eq 0 ]
  then
    TAGS=$(cat $RAW| tr '[' "\n" | tr ']' "\n" | grep "Catégorie" | sed -e 's/.*://' -e 's/|.*//g'| tr '[:upper:]' '[:lower:]'| sed -e 's/^/"/' -e 's/$/"/' | tr "\n" ",")
    TAGS="$TAGS \"mediawiki\""

    ICON=$(shuf -n 1 $DIR/icons.lst)
    COLOR=$(shuf -n 1 $DIR/colors.lst)

    echo "+++"                      > $DST
    echo "date = \"$DATE\""         >> $DST
    echo "draft = false"            >> $DST
    echo "title = \"$TITLE\""       >> $DST
    echo "color = \"$COLOR\""       >> $DST
    echo "icon = \"$ICON\""         >> $DST
    echo "Tags = [$TAGS]"           >> $DST
    echo "description = \"$TITLE\"" >> $DST
    echo "+++"                      >> $DST
    echo ""                         >> $DST
    cat $RAW | \
      sed -e 's/\[\[Catégorie[^]]*\]\]//g' -e 's/:Catégorie://g' | \
      pandoc -f mediawiki -t markdown >> $DST
    echo "OK"
  else 
    rm -rf $DST
    echo "."
  fi
done

#+++
#date = "2015-01-28T15:42:50+01:00"
#draft = true
#title = "about"
#tags = ["x", "y"]
#
#+++


# Correction des liens
for file in $CONTENT/*.md
do
  echo $file
  sed -f $CACHE/links.sed -i $file
done
